### ISSUE TITLE
Question about extensions & roadmap

### ISSUE THREAD

**Issue by jtrivett** [paypal/butterfly#358]
Hello,

First, thanks for this project, it looks like it could be really useful for some repeatable application modernization tasks I have. This is not an issue per se, but I have a few questions for the maintainers (I didn't see another way to get in contact).

- Extensions: I have not found any aside from the sample extension in the Getting Started guide. Has paypal (or others) contributed any open source extensions that can be reused by others? Is there a catalog/repository of extensions somewhere?

- Roadmap: What is the roadmap for this project? I'd like to understand if it is still being actively developed and supported.

Thanks for your time!

**Comment by fabiocarvalho777** [comment]
Hello Jason,

Thanks for your words and question as well.

Regarding extensions, PayPal has 4 active extensions being used over the past 4 years processing a total of 1600 applications, and performing around 100 transformations per day. We also have a 5th extension under development at the moment. All those extensions are proprietary though, since they are all very PayPal specific. PayPal also has developed many Transformation Utilities and Operations over this time. Most of them were open sourced.

When it comes to an extension catalog, we did expect to have it, [and have this folder for that](https://github.com/paypal/butterfly/tree/master/extensions-catalog), but right now the only open source extension we have is the Spring Boot one. We would love to have more though. Any user can contribute.

Regarding project roadmap and activity, even though recent commit history is not very active (tool is very mature and stable at this point), the project is very active, with many users using it daily, as I mentioned in previous answer.

Let us know if you have any other question. If you have interest in using Butterfly, I would be glad to informally collaborate with you and your team closely. This tool is maintained today at PayPal by a team of 5 people led by me. We also have many other contributors from the teams who use it internally at PayPal.

PRs (with bug fixes and enhancements) form the open source community are also always welcome, and new ideas too.

Have a good week.

**Comment by jtrivett** [comment]
Fábio,

This is very reassuring to hear, and I appreciate your quick response. I'm going to spend some time evaluating butterfly to see how it can support some of the transformations my company is doing at the moment. If it all goes well, perhaps we'll have some opportunities to contribute utilities or extensions to this project.

Thanks for the offer to collaborate. If I have questions or comments while evaluating, may I contact you directly via the email address in your profile?

**Comment by fabiocarvalho777** [comment]
If you have questions or comments you can contact me at facarvalho@paypal.com

Thanks!
